import { beforeEach, describe, expect, it, vi } from 'vitest';
const h = vi.hoisted(() => ({ user: { id: 'owner' }, mode: 'shadow' as 'shadow'|'off'|'active', result: { ok: true, status: 'completed', reply: 'done' }, chat: vi.fn(), callbacks: [] as Array<() => unknown>, shadow: vi.fn(), record: vi.fn(), created: { ok: true, nodeId: 'node-id' } as { ok: boolean; nodeId: string | undefined }, owns: true, ownershipReads: 0 }));
vi.mock('server-only', () => ({}));
vi.mock('next/server', () => ({ after: (fn: () => unknown) => { h.callbacks.push(fn); } }));
vi.mock('next/cache', () => ({ revalidatePath: vi.fn() }));
vi.mock('@/lib/supabase/server', () => ({ createClient: async () => ({ auth: { getUser: async () => ({ data: { user: h.user } }) }, from: (table: string) => { const q = { select: () => q, eq: () => q, maybeSingle: async () => ({ data: table === 'works' ? (h.ownershipReads++ === 0 || h.owns ? { id: 'w' } : null) : { id: 'chapter' } }) }; return q; } }) }));
vi.mock('@/lib/supabase/admin', () => ({ createAdminClient: () => ({}) }));
vi.mock('@/lib/ai/chat', () => ({ chat: h.chat }));
vi.mock('@/lib/ai/providers/registry', () => ({ createPlatformProvider: () => ({ provider: 'gemini' }) }));
vi.mock('@/lib/ai/decision/activation', () => ({ getAiDocPlanningMode: async () => ({ mode: h.mode, reasons: [], modelVersion: 'jev' }) }));
vi.mock('@/lib/ai/decision/jev', () => ({ createJevClient: () => ({ provider: 'jev' }) }));
vi.mock('@/lib/ai/decision/fixture', () => ({ readDecisionFixture: () => null, createFixtureDecisionClient: vi.fn() }));
vi.mock('@/lib/ai/decision/shadow', () => ({ runShadowPlan: h.shadow, recordDocumentSaveDecision: h.record }));
vi.mock('@/lib/ai/providers/fixture', () => ({ readProviderFixture: () => null }));
vi.mock('@/lib/ai/mentions', () => ({ searchMentionNodes: vi.fn(), quickAddMentionNode: vi.fn() }));
vi.mock('@/lib/access/actions', () => ({ readChapterContent: vi.fn() }));
vi.mock('@/lib/chapters/actions', () => ({ saveChapterContent: vi.fn(), publishChapter: vi.fn(), unpublishChapter: vi.fn() }));
vi.mock('@/lib/kb/actions', () => ({ validateTargetFolder: async () => ({ ok: true }), validateTargetTemplate: async () => ({ ok: true }), createNode: async () => h.created, saveNodeContent: vi.fn(), listCategoryFolderCandidates: vi.fn(), listTemplateOptions: vi.fn() }));
import { chatAction, saveDocumentProposalAction } from '@/app/studio/[workId]/chapters/[chapterId]/actions';
import { KB_CATEGORIES } from '@/lib/kb/categories';
const key = '6f1c2b1e-3d4a-4b5c-8d9e-0a1b2c3d4e5f';
const workId = '11111111-1111-4111-8111-111111111111';
const input = (overrides: Record<string, unknown> = {}) => ({ workId, chapterId: 'chapter', providerId: 'gemini', model: 'gemini-3.5-flash', mentionedNodeIds: ['fact'], presetLevel: 'balanced', styleId: 'default', genre: 'fantasy', precedingText: 'chapter context', chatHistory: [{ role: 'user', content: 'actual private prompt' }], idempotencyKey: key, ...overrides }) as unknown as Parameters<typeof chatAction>[0];
beforeEach(() => { h.mode = 'shadow'; h.callbacks.length = 0; h.shadow.mockReset(); h.record.mockReset(); h.chat.mockReset().mockResolvedValue(h.result); h.created = { ok: true, nodeId: 'node-id' }; h.owns = true; h.ownershipReads = 0; });
describe('Jev shadow action wiring', () => {
 it('schedules metadata-only shadow work after returning chat result', async () => { expect(await chatAction(input())).toBe(h.result); expect(h.callbacks).toHaveLength(1); await h.callbacks[0](); expect(h.shadow).toHaveBeenCalledWith(expect.anything(), { ownerId: 'owner', workId, requestKey: key, requestLength: 21, hasChapterContext: true, mentionedFactCount: 1 }); });
 it.each(['off','active'] as const)('does not schedule in %s mode', async mode => { h.mode = mode; await chatAction(input()); expect(h.callbacks).toHaveLength(0); });
 it('registers based on mode despite refused chat and returns its result', async () => { h.chat.mockResolvedValue({ ok: false, status: 'refused' }); expect(await chatAction(input())).toEqual({ ok: false, status: 'refused' }); expect(h.callbacks).toHaveLength(1); });
 it('checks work ownership before invoking shadow', async () => { h.owns = false; await chatAction(input()); await h.callbacks[0](); expect(h.shadow).not.toHaveBeenCalled(); });
 it('logs successful save recommendation after response with actual selected values', async () => { await saveDocumentProposalAction({ workId, proposal: { category: KB_CATEGORIES[0], name: 'N', content: 'C', recommendedFolderId: '22222222-2222-4222-8222-222222222222', recommendedTemplateId: '33333333-3333-4333-8333-333333333333' }, targetFolderId: '44444444-4444-4444-8444-444444444444', templateId: '55555555-5555-4555-8555-555555555555', regenerated: true }); expect(h.callbacks).toHaveLength(1); await h.callbacks[0](); expect(h.record).toHaveBeenCalledWith(expect.anything(), expect.objectContaining({ nodeId: 'node-id', actualFolderId: '44444444-4444-4444-8444-444444444444', actualTemplateId: '55555555-5555-4555-8555-555555555555', regenerated: true })); });
 it('does not log failed save', async () => { h.created = { ok: false, nodeId: undefined }; const result = await saveDocumentProposalAction({ workId, proposal: { category: KB_CATEGORIES[0], name: 'N', content: 'C', recommendedFolderId: '22222222-2222-4222-8222-222222222222' }, targetFolderId: '44444444-4444-4444-8444-444444444444', templateId: null, regenerated: false }); expect(result.ok).toBe(false); expect(h.callbacks).toHaveLength(0); });
});
